server:
  port: 8888
spring:
  application:
    name: forum
  ##数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=UTC
    username: root
    password: Lilongfu8
  ##redis配置
  data:
    redis:
      host: 192.168.26.130
      port: 6379
      password: Lilongfu8
  ##导入多个配置文件
  config:
    import: conf/info.yml
  ##设置文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB  # 设置单个文件的最大大小
      max-request-size: 100MB  # 设置整个请求的最大大小

##mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    ##开启驼峰命名
    map-underscore-to-camel-case: true
  ##对pojo取别名
  type-aliases-package: com.hnust.pojo
  mapper-locations: classpath:repository/**

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true


